version: '3.8'

services:
  api:
    build: .
    container_name: marathon_api
    restart: always
    volumes:
      - ./models:/app/models
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - MODEL_PATH=models/
      - ALLOWED_ORIGINS=https://tu-dominio.digitalocean.com,http://tu-dominio.digitalocean.com
      - API_HOST=0.0.0.0
      - API_PORT=8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app_network

networks:
  app_network:
    driver: bridge